name: New Submarine Request
description: This form is used to request a new submarine/USV.
# title: "New Submarine: "
labels: ["addition", "submarine"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a new sub request!

        ### On Class Requests
        If you're requesting an entire class of sub rather than a specific vessel, please fill out the form as if for the class nameship. For example, if requesting the Virginia-class, fill out the form as if for SSN-774.

        If the class saw significant changes/blocks/flights/etc., it may be worth filing separate requests to cover these differences. Please fill out the follow-on forms as if for the block/flight nameship. For example, if requesting the Flight II Virginia-class, fill out the form as if for SSN-778.

        ### ...Okay, how much of this do I *really* need to fill out?
        Although only some of these fields are "required," please do your best to supply as much information as possible. What you don't give us, we need to hunt down ourselves or estimate.

        If you can't (or don't want) to provide this information, consider whether filing a DB request will be helpful.

  - type: markdown
    attributes:
      value: |
        ## Basic Information
        Please provide some basic information on the sub. 
        
        This is used to determine how the sub appears in-sim and in the DB viewer.

  - type: checkboxes
    attributes:
      label: Hypothetical
      description: Is this a hypothetical vessel, i.e. one not yet or never placed in service?
      options:
        - label: "Yes"
          required: false

  - type: input
    attributes:
      label: Name
      description: Provide classification, pennant number, and name (where applicable).
      placeholder: ex. SS-161 Stingray
    validations:
      required: true

  - type: input
    attributes:
      label: Class
      placeholder: ex. Balao-class
    validations:
      required: false

  - type: input
    attributes:
      label: Country
      placeholder: ex. United States
    validations:
      required: false

  - type: input
    attributes:
      label: In Commission
      description: |
        When was the *class* in service?
        
        If requesting a specific vessel, this will match the vessel's service dates. If requesting a class (and therefore modelling a nameship), the out-of-service date may be much later than the nameship's decommissioning.
      placeholder: ex. 1943-1971
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Dimensions and Tonnage
        Please provide measurements for the sub.
        
        This is used to determine a number of critical factors in-sim, including "damage points" (DP), signature, etc.

  - type: input
    attributes:
      label: Length (m)
      placeholder: ex. 95
    validations:
      required: true

  - type: input
    attributes:
      label: Beam (m)
      placeholder: ex. 8.3
    validations:
      required: true

  - type: input
    attributes:
      label: Draft (m)
      placeholder: ex. 5.1
    validations:
      required: true

  - type: input
    attributes:
      label: Standard Displacement (t)
      description: Interchangeable with normal. If only a single number is provided for displacement, assume it's standard.
    validations:
      required: true

  - type: input
    attributes:
      label: Submerged Displacement (t)
    validations:
      required: false

  - type: input
    attributes:
      label: Empty Displacement (t)
    validations:
      required: false

  - type: input
    attributes:
      label: Max Depth (m)
    validations:
      required: true

  - type: input
    attributes:
      label: Complement
      placeholder: ex. 31
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Propulsion
        Please provide some information on propulsion, speeds, etc. for the sub.

  - type: dropdown
    attributes:
      label: Primary Propulsion Type
      multiple: false
      options:
        - Nuclear
        - Diesel/Electric
        - Diesel/Electric w/ AIP
        - Electric (UUVs)
    validations:
      required: true

  - type: input
    attributes:
      label: Propulsion
      description: Number, make, and type of primary engines. For diesel-electric subs, this will be the diesel engines.
      placeholder: ex. 4x Fairbanks-Morse Model 38D8 Diesels
    validations:
      required: true

  - type: input
    attributes:
      label: Flank Speed at Surface (kt)
    validations:
      required: true

  - type: input
    attributes:
      label: Flank Speed Submerged (kt)
    validations:
      required: false

  - type: input
    attributes:
      label: Range (nm) at Speed (kt)
      description: This will usually be at the sub's cruise speed.
      placeholder: ex. 1000nm @ 15kts
    validations:
      required: true

  - type: input
    attributes:
      label: Range (nm) on AIP
      description: If the sub is capable of AIP, how far is its range when using this method of propulsion?
      placeholder: ex. 850
    validations:
      required: false

  - type: input
    attributes:
      label: Fuel Capacity (kg)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Sensing & Shooting
        Please list as many of the sub's sensors and mounts (i.e. weapons) as you can.

  - type: textarea
    attributes:
      label: Sensors
      description: | 
        List the sub's sensors. All of them, if you can -- not just the most important ones. If you don't know an exact model, record a generic and provide as much supplementary information as you can.

        Please place each mount on a new line as in the example.
      placeholder: |
        1x OMS 100 / SERO 400 Periscope Suite
        1x Type 1007 Radar
        1x DBQS-40 Sonar
    validations:
      required: true

  - type: textarea
    attributes:
      label: Mounts
      description: |
        List the sub's mounts (i.e., weapons): guns, missiles, torpedoes, VLS, etc.

        Please place each mount on a new line as in the example.
      placeholder: |
        6x 533mm TT (BSA Torpedoes)
        2x TAU-2000 DL
    validations:
      required: true

  - type: textarea
    attributes:
      label: Magazines
      description: |
        Describe the sub's available reloads, if known and applicable.
      placeholder: |
        6x BSA Torpedoes
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Miscellanious Capabilities
        Finally, please describe any other special capabilities the sub has.

  - type: textarea
    attributes:
      label: Comms/Datalinks
      description: |
        List any known comms systems or datalinks, placing each mount on a new line as in the example.
      placeholder: |
        VHF/UHF Radio [Secure]
        SATCOM
        Link 11
        Link 14
        Link 16
    validations:
      required: false

  - type: dropdown
    attributes:
      label: sub Codes
      description: Indicate which (if any) of the following DB codes apply to this vessel.
      multiple: true
      options:
        - Shock Resistant
        - Nonmagnetic Hull
        - Titanium Hull
        - Double Hull
        - Shrouded Propulsor
        - Advanced Propulsor
        - Lithium-Ion Batteries
        - Snorkel
        - No Launch Transient
        - Low Construction Standards
        - Laid Down Before 1930

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    attributes:
      label: Comments
      description: Anything else you think we need to know in order to effectively model this platform.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. If offline, provide title, author, and page.

        We do check these where possible. If we can't corroborate your information, we may provide replacements from our own sources or discard your request entirely.
    validations:
      required: true