name: New Facility Request
description: This form is used to request a new facility (SAMs, SSMs, etc.).
# title: "New Facility: "
labels: ["addition", "facility"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a new facility request!

        ### Facility or Ground Unit?
        As a rule of thumb, if the system is defined by the effect it has *on other domains*, it's probably best modelled as a facility. A SAM system, for example, is meant to engage targets in the air; a coastal defense missile battery is intended to engage targets at sea; this despite both technically being land-based platforms.

        Modelling as a Ground Unit is more appropriate for land combat vehicles, i.e. vehicles whose primary purpose is to spot, engage, and destroy other targets on land or otherwise influence operations in that domain. Tanks, APCs/IFVs, trucks, and cars are all examples of vehicles best modelled in the Ground Units annex.

        ### ...Okay, how much of this do I *really* need to fill out?
        Although only some of these fields are "required," please do your best to supply as much information as possible. What you don't give us, we need to hunt down ourselves or estimate.

        If you can't (or don't want) to provide this information, consider whether filing a DB request will be helpful.

  - type: markdown
    attributes:
      value: |
        ## Basic Information
        Please provide some basic information on the facility. 
        
        This is used to determine how it will appear in-sim and in the DB viewer.

  - type: checkboxes
    id: hypo
    attributes:
      label: Hypothetical
      description: Is this a hypothetical facility, i.e. one not yet or never placed in service?
      options:
        - label: "Yes"
          required: false

  - type: input
    id: name
    attributes:
      label: Name
      description: Provide a name for the facility.
      placeholder: ex. SSM Btn (SM-62A Snark)
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Facility Type
      description: Choose the type descriptor that best describes this facility. In most cases this will match the name.
      multiple: true
      options:
        - Radar
        - SAM
        - AAA
        - Arty
        - SSM
        - Armored
        - Inf
        - Mech
        - Motor
        - Ammo
        - Fuel
        - Supply

  - type: input
    id: operatorcountry
    attributes:
      label: Country
      placeholder: ex. United States
    validations:
      required: false

  - type: input
    id: operatorservice
    attributes:
      label: Service
      placeholder: ex. Army
    validations:
      required: false

  - type: input
    id: in-service
    attributes:
      label: In Commission
      description: When was the facility in-service with the aforementioned country and service?
      placeholder: ex. 1959-1961
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Seeing & Shooting
        Please list the facility's primary sensors and mounts where applicable.

  - type: textarea
    id: sensors
    attributes:
      label: Sensors
      description: |
        List the facility's sensors, placing each on a new line as in the example.
      placeholder: |
        1x KALKAN-II Radar
        1x ASELFLIR-300D EOS
    validations:
      required: true

  - type: textarea
    id: mounts
    attributes:
      label: Mounts
      description: |
        List the facility's mounts (weapons), placing each on a new line.
      placeholder: |
        3x HISAR-A TEL
    validations:
      required: true

  - type: textarea
    id: mounts
    attributes:
      label: Magazines
      description: |
        Describe the facility's available on-site reloads, if known and applicable.
      placeholder: |
        24x HISAR-A Missles
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Miscellanious Specifications

  - type: input
    id: crew
    attributes:
      label: Crew
      placeholder: ex. 40
    validations:
      required: false

  - type: input
    id: disp-rad
    attributes:
      label: Dispersion Radius (m)
      description: How far apart are the individual "mounts" usually positioned? For example, in a SAM site, how far apart are the TELs?
      placeholder: ex. 40
    validations:
      required: false      

  - type: textarea
    id: facilities
    attributes:
      label: Aircraft & Docking Facilities
      description: List any docking and/or aircraft facilities, placing each on a new line.
      placeholder: |
        1x Pad (Medium Aircraft)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Final Touches

  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Anything else you think we need to know in order to effectively model this platform.
    validations:
      required: false

  - type: textarea
    id: sources
    attributes:
      label: Sources
      description: |
        Please list all the sources you used to find the information you provided. If offline, provide title, author, and page.

        We do check these where possible. If we can't corroborate your information, we may provide replacement data from our own sources or discard your request entirely.
    validations:
      required: true